spring.application.name=sb-ecom

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#diff between create and create-drop -> in a new session the existing will be dropped and new will be created that is create
#and in create drop -= created during start of application and dropped at end of
#application/session means it does not wait for another session to drop basically only exists between lifecycle of a application
#spring.jpa.hibernate.ddl-auto=create-drop


project.image=images/